[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C", "N", "T", "B"]
extend-ignore = ["E203", "W503"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
