name: Build & Push ECR
on:
  push:
    tags: ['v*']
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1
  ECR_REPO: ada-slope-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push
        working-directory: backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.ref_name }}
          ECR_REPO: ${{ env.ECR_REPO }}
        run: |
          docker build -t $ECR_REPO:latest .
          docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:latest
          docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:latest
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
      - name: Output image URI
        run: |
          echo "Image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.ref_name }}"
