name: Lint & Test

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'tests/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          pip install ruff pytest pytest-cov

      - name: Run ruff
        run: |
          ruff check .

      - name: Run tests
        env:
          PYTHONPATH: backend
        run: |
          pytest -q --maxfail=1 --disable-warnings
