name: Python CI
on:
  pull_request:
    paths:
      - 'backend/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/python-ci.yml'
jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff black mypy pytest pytest-cov hypothesis
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .
      - name: Mypy (types)
        run: mypy backend || true
      - name: Pytest
        env: { PYTHONPATH: backend }
        run: pytest -q --maxfail=1 --disable-warnings --cov=backend/app --cov-report=term-missing
