name: Terraform Plan
on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-plan.yml'
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  AWS_REGION: us-east-1
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false
      - name: Terraform Fmt
        working-directory: infra
        run: terraform fmt -check
      - name: Terraform Validate
        working-directory: infra
        run: terraform validate
      - name: Terraform Plan (capture output)
        working-directory: infra
        run: terraform plan -no-color | tee ../plan.txt
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.txt
